# Generated by Django 4.2.2 on 2023-12-24 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_bankpersonnel_user_address_user_city_and_more'),
        ('loans', '0001_initial'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancustomer',
            name='loans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loancustomer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='loancustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankpersonnel',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='banks.branch'),
        ),
        migrations.AddField(
            model_name='bankpersonnel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='bankpersonnel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='bankpersonnel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='bankpersonnel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_personnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loanprovider',
            index=models.Index(fields=['id'], name='authenticat_id_cae34a_idx'),
        ),
        migrations.AddIndex(
            model_name='loanprovider',
            index=models.Index(fields=['user'], name='authenticat_user_id_3b0a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='loancustomer',
            index=models.Index(fields=['id'], name='authenticat_id_76f0c1_idx'),
        ),
        migrations.AddIndex(
            model_name='loancustomer',
            index=models.Index(fields=['user'], name='authenticat_user_id_eee356_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpersonnel',
            index=models.Index(fields=['id'], name='authenticat_id_89a443_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpersonnel',
            index=models.Index(fields=['user'], name='authenticat_user_id_4d3690_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpersonnel',
            index=models.Index(fields=['branch'], name='authenticat_branch__d96c54_idx'),
        ),
    ]
