# Generated by Django 4.2.2 on 2023-12-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_loancustomer_loans_loancustomer_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancustomer',
            name='loans',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at'], name='authenticat_deleted_7262c1_idx'),
        ),
    ]
