# Generated by Django 4.2.2 on 2023-12-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_authenticat_id_9bf31e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='authenticat_deleted_6dfccb_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='authenticat_deleted_d736dc_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='authenticat_id_9bf31e_idx'),
        ),
    ]
