# Generated by Django 4.2.2 on 2023-12-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_authenticat_deleted_6dfccb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancustomer',
            name='monthly_income',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
