# Generated by Django 4.2.2 on 2023-12-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('authentication', '0009_loancustomer_monthly_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancustomer',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_applicants', to='banks.bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loancustomer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='loanprovider',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_applicants', to='banks.bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanprovider',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
