# Generated by Django 4.2.2 on 2023-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_bankpersonnel_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancustomer',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanprovider',
            name='total_funds',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
