# Generated by Django 4.2.2 on 2023-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bank_created_by_alter_bank_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='available_funds',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='bank',
            name='total_funds',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
