# Generated by Django 4.2.2 on 2023-12-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_alter_bank_available_funds_alter_bank_total_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='total_loans',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='bank',
            name='available_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='bank',
            name='total_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
