# Generated by Django 4.2.2 on 2023-12-25 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_authenticat_deleted_6dfccb_idx_and_more'),
        ('loans', '0002_alter_loan_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='providers',
        ),
        migrations.AddField(
            model_name='loan',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='authentication.loanprovider'),
            preserve_default=False,
        ),
    ]
