# Generated by Django 4.2.2 on 2023-12-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('loans', '0003_remove_loan_providers_loan_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='banks.bank'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['id'], name='loans_loan_id_e9d62c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['provider'], name='loans_loan_provide_c94afb_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['bank'], name='loans_loan_bank_id_665270_idx'),
        ),
    ]
