# Generated by Django 4.2.2 on 2023-12-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('loans', '0004_loan_bank_loan_loans_loan_id_e9d62c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanplan',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loan_plans', to='banks.bank'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='loanplan',
            index=models.Index(fields=['bank'], name='loans_loanp_bank_id_d95500_idx'),
        ),
    ]
