# Generated by Django 4.2.2 on 2023-12-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_created_by_alter_loan_deleted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='released_at',
            new_name='disbursed_at',
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_payable_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_payable_amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
