# Generated by Django 4.2.2 on 2023-12-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_rename_released_at_loan_disbursed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'managed': True, 'permissions': [('can_approve_loan', 'Can approve loan'), ('can_reject_loan', 'Can reject loan'), ('can_disburse_loan', 'Can disburse loan')]},
        ),
    ]
