# Generated by Django 4.2.2 on 2023-12-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_loan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='interest_paid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='principal_paid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
