# Generated by Django 4.2.2 on 2023-12-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_loanpayment_interest_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='interest_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='principal_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
