# Generated by Django 4.2.2 on 2023-12-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_loanpayment_interest_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanpayment',
            options={'managed': True, 'permissions': [('can_pay_loan', 'Can pay loan'), ('can_view_amortization_schedule', 'Can view amortization schedule')]},
        ),
    ]
