# Generated by Django 4.2.2 on 2023-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_alter_loanpayment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('released', 'Released'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
