# Generated by Django 4.2.2 on 2023-12-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_alter_loan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
